name: Docker Image CI

on:
  repository_dispatch:
    types: [docker-build]

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build .  --tag docker.io/linuxoid69/go-backuper:0.1.0
