name: Docker Image CI

on:
  repository_dispatch:
    types: [docker-build]
# env:
#   APP_VERSION: 0.2.2

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get an artifact
      run: |
        export ARTIFACT=$(curl -L "https://api.github.com/repos/linuxoid69/go-backuper/actions/artifacts" \
        -H "Accept: application/vnd.github.full+json" \
        -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" | jq ".artifacts | .[0] | .archive_download_url") \
         && curl -L $(echo ${ARTIFACT} | sed -r s#\"##g) \
         -H "Accept: application/vnd.github.full+json" \
         -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" -o go-backuper.zip && unzip go-backuper.zip

    - name: Build the Docker image
      run: |
        echo "my var: ${{ github.event.client_payload.version }}"
        docker build .  --tag docker.io/linuxoid69/go-backuper:${{ github.event.client_payload.version }}
        docker tag docker.io/linuxoid69/go-backuper:${{ github.event.client_payload.version }} docker.io/linuxoid69/go-backuper:latest

    - name: Deploy the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push docker.io/linuxoid69/go-backuper:${{ github.event.client_payload.version }}
        docker push docker.io/linuxoid69/go-backuper:latest
