name: Go

on:
  push:
    branches: [ master ]

env:
  APP_VERSION: 0.2.3

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        if [ -f go.mod ]; then
          go mod vendor
        else
          go get -v -t -d ./...
        fi

    - name: Build
      run: go build -ldflags="-s -w -X main.version=${{ env.APP_VERSION }} -X main.commit=${{ GITHUB_SHA }}" -v .

    - uses: actions/upload-artifact@v1
      with:
        name: go-backuper-${{ env.APP_VERSION }}
        path: go-backuper

    - name: Docker Image CI
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: docker-build
        client-payload: '{"version": "${{ env.APP_VERSION }}"}'
